/**
 * African Blowling game
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';
import {HttpClient, HttpHeaders} from '@angular/common/http';


import {AfricanBowlingGame} from '../model/africanBowlingGame';
import {Observable} from 'rxjs';


declare var window: any;


@Injectable()
export class GameApiService {

  public basePath = 'http://localhost:8080';
  public defaultHeaders = new HttpHeaders();

  private readonly applicationJson = 'application/json';
  private readonly contentType = 'Content-Type';

  constructor(protected httpClient: HttpClient) {
    if (!!window.serverUrl) {
      this.basePath = window.serverUrl;
    }
  }


  /**
   * Update the game based on throw value
   *
   * @param body
   */
  public lancer(body?: number): Observable<AfricanBowlingGame> {

    const headers = this.defaultHeaders;

    headers.set('Accept', this.applicationJson);
    headers.set(this.contentType, this.applicationJson);
    return this.httpClient.request<AfricanBowlingGame>('patch', `${this.basePath}/games`,
      {
        body: body,
        headers: headers,
      }
    );
  }

  /**
   * start a new Game
   *
   */
  public startNewGame(): Observable<AfricanBowlingGame> {
    const headers = this.defaultHeaders;

    headers.set('Accept', this.applicationJson);
    headers.set(this.contentType, this.applicationJson);

    return this.httpClient.request<AfricanBowlingGame>('post', `${this.basePath}/games`,
      {
        headers: headers,
      }
    );
  }

}
