version: '3.7'
services:
  server:
    image: gauthierrobert/abg-server:latest
    ports:
      - '8081:8080'

  front:
    image: gauthierrobert/abg-gui:latest
    ports:
      - '4201:80'
    environment:
      SERVER_URL: http://localhost:8081
    depends_on:
      - server